version: '3'

services:
  redis:
    image: "redis:alpine"
    hostname: redis
    ports:
      - "6379:6379"

  zoo1:
    image: zookeeper:3.4.9
    hostname: zoo1
    ports:
      - "2181:2181"
    environment:
      ZOO_MY_ID: 1
      ZOO_PORT: 2181
      ZOO_SERVERS: server.1=zoo1:2888:3888
    volumes:
      - ./zk-single-kafka-single/zoo1/data:/data
      - ./zk-single-kafka-single/zoo1/datalog:/datalog
    depends_on:
      - redis

  kafka1:
    image: confluentinc/cp-kafka:5.4.1
    hostname: kafka1
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_LISTENERS: LISTENER_DOCKER_INTERNAL://kafka1:19092,LISTENER_DOCKER_EXTERNAL://${DOCKER_HOST_IP:-127.0.0.1}:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: LISTENER_DOCKER_INTERNAL:PLAINTEXT,LISTENER_DOCKER_EXTERNAL:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: LISTENER_DOCKER_INTERNAL
      KAFKA_ZOOKEEPER_CONNECT: "zoo1:2181"
      KAFKA_BROKER_ID: 1
      KAFKA_LOG4J_LOGGERS: "kafka.controller=INFO,kafka.producer.async.DefaultEventHandler=INFO,state.change.logger=INFO"
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    volumes:
      - ./zk-single-kafka-single/kafka1/data:/var/lib/kafka/data
    depends_on:
      - zoo1
      - redis

  consumer-service:
    restart: on-failure
    container_name: consumer-service-container
    build:
      context: .
      dockerfile: consumer/Dockerfile_consumer
    image: consumer-service:latest
    ports:
      - 9001:8085
      - 9009:9009
    volumes:
      - consumer-service:/data/consumer-service
    logging:
      driver: json-file
    environment:
      - TZ=Europe/Tallinn
      - SPRING_PROFILES_ACTIVE=prod
    depends_on:
      - zoo1
      - redis

  daemon-service:
    restart: on-failure
    container_name: daemon-service-container
    build:
      context: .
      dockerfile: daemon/Dockerfile_daemon
    image: daemon-service:latest
    ports:
      - 9002:8086
      - 9010:9010
    volumes:
      - daemon-service:/data/daemon-service
    logging:
      driver: json-file
    environment:
      - TZ=Europe/Tallinn
      - SPRING_PROFILES_ACTIVE=prod
    depends_on:
      - zoo1
      - redis

volumes:
  zk-single-kafka-single:
  consumer-service:
  daemon-service: